#include "rwmake.ch"
//#DEFINE MAXPASSO 1600
//#DEFINE MAXPASSO1 1700

/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณ_REGUAS   บAutor  ณ Renato K. Ikeda    บ Data ณ  06/13/03   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ Exemplo de 2 reguas de processamento                       บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/

User Function Regua()
oProcess := MsNewProcess():New({|| CtRe190Proc(oProcess)},"","",.F.)
oProcess:cTitle:="Teste Regua"  //Tํtulo da Tela de Processamento
oProcess:Activate()		
Return


Static Function CtRe190Proc(oProcess)
//Local i
//Local j
oProcess:SetRegua1(50)	
For i:=1 to 50
	oProcess:IncRegua1("Atualizando Regua1:  "+STR(i))//Incrementa primeira r้gua
	
	oProcess:SetRegua2(1700)
	For j:=1 to 1700
		oProcess:IncRegua2("Atualizando Regua2:  "+STR(j))//Incrementa segunda r้gua
	Next J
Next I

//oProcess:SetRegua2(6000)
//For j:=1 to 6000
//	oProcess:IncRegua2("Atualizando Regua2:  "+STR(j))//Incrementa segunda r้gua
//Next

Return